[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-rt = "2.7.0"
actix-web = "4.0.1"
reqwest = "0.11.10"
tokio = "1.17.0"
